Solidity doc cn B
etherchina/solidity-doc-cn pull request #93
Opened 2018-05-15 23:08 UTC by dennisWind

This reverts commit 21d97c0d31c4953bda743ad5012f913e0cbf5677, reversing
changes made to 2606676bdc606ddf418397655f1034f588c427e9.

2018-05-16 01:57 UTC, riversyang commented
refer to issue #15

2018-05-16 13:03 UTC, riversyang requested changes

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +可以通过以太坊交易 "从外部" 或从 Solidity 合约内部创建合约。
引号应该用中文，参见中文排版说明。（除了直接引用英文原文或者代码段的地方，其他地方的标点符号需要统一使用中文标点，下同。）

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +集成开发环境，像 `Remix <https://remix.ethereum.org/>`_, 使用用户界面元素流畅的创建合约。
这句译文的意思没问题，但语序明显英文化，我大概会调整为：
像 `Remix <https://remix.ethereum.org/>`_ 这样的 IDE，通过使用一些用户界面元素使创建过程更加流畅。
另外注意标点符号需要使用中文标点。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +从今天开始，有一个名为 `web3.eth.Contract <https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#new-contract>`_ 的方法能够更容易的创建合约。
As of today，中文里不应该直译为“从今天开始”，这里前半句可以简单地译为：现在，我们已经有了一个叫做 ...
另外，实际上 web3 的 1.0 版本还没有 release，所以这里说的这个方法在主网上还不能用。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +在内部，构造函数参数在合约代码之后通过 :ref:`ABI 编码 <ABI>`，但是如果你使用 ``web3.js``
原文中的 are passed 译漏了。... 通过 :ref:`ABI 编码 <ABI>` 传递，...

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +如果一个合约想要创建另一个合约，那么创建者必须知晓被创建合约的源代码(和二进制)。
binary，指的是字节码，或者二进制代码。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // 这是注册 creator 和分配名称的构造函数。
assign 在这里译为“设置”更恰当，这个 name 并没有“分配”给别的合约。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 状态变量通过其名称访问，而不是通过例如 this.owner.
最后的句号应该用中文标点。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 这也适用于函数，特别是在构造函数中，你只能那样调用他们（"内部调用"），
最后半句，建议改为：你只能像这样（“内部地”）调用它们。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 并且假定调用合约的类型是 TokenCreator，没有真正的检查方法。
后半句建议改为：没有真正的方法来检查这一点。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 只有 creator 能够更改名称 -- 因为合约是隐式转换为地址的，
这里可以给 creator 加个括号注释：即创建当前合约的合约。
-- 应该用中文破折号 ——

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 只有当前所有者才能传送权证
token 建议不要译了，下文同。另外，transfer，一般译为“发送”比较符合中文习惯。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 我们还想确认 creator 是否权证转移是正常操作。
这句不通。可以简单译为：我们也想询问 creator 是否可以发送。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 创建一个新的权证合约并且返回它的地址。
Token 不要译了。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 从 JavaScript 方面来说，返回类型是简单的 `address` 类型，这是因为
这是因为，“这是”是多余的。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 这是在 ABI 中最接近的类型。
这是在 ABI 中可用的最接近的类型。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +由于 Solidity 有两种函数调用（内部调用不会产生实际的 EVM 调用（也称为
括号里那句话译错了，应该是：内部调用不会产生实际的 EVM 调用（也称为“消息调用”）而外部调用则会（产生一个 EVM 调用）

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +一个“消息调用”）和外部调用），有四种函数可见性类型和状态变量。
最后半句也译错了，应该是：函数和状态变量有四种可见性类型

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    ``f`` 不能从内部调用（比如 ``f`` 不起作用，但 ``this.f()`` 可以）。
i.e. 是拉丁词 ID EST 的缩写，不是例如或者比如的意思（不是 e.g.），中文大概可以译为：即、也就是说、相当于。这里建议译为：也就是说

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    公共函数是合约接口的一部分，可以在内部或通过消息调用。对于公共状态变量，
public 是关键字，不要译了。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    私有函数和状态变量仅在当前定义它们的合约中使用，并且不能被派生合约使用。
private 在作为关键字，在这句里还是不要译了。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +可见性的标识符的定义位置，对于状态变量来说是在类型后面，对于函数是在参数列表和返回关键字中间。
可见性的，“的”应该删掉。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +使用修改器可以轻松改变函数的行为。 例如，它们可以在执行该功能之前自动检查条件。 修改器是合约的可继承属性，
第二句译文不太准确。建议改为：例如，它们可以在执行函数之前自动检查某个条件。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // 将函数体插入到特殊符号 `_;` 出现的位置。
这句译文的表述不太通顺，建议改为：修改器所修饰的函数体会被插入到特殊符号 `_;` 的位置。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // 这意味着如果是 owner 调用这个函数，则函数会被执行，否则则会抛出异常。
否则则，去掉一个“则”也是通顺的。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // 这个合约从 `owned` 继承了 `onlyOwner` 修饰符，并并将其应用于 `close` 函数，
并并将，手误

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // 只有存储的拥有者调用 `close` 函数，才会生效。
stored owner，指的是在合约里保存的 owner，就是在 owned 合约里定义的那个合约级变量 owner。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // 重要的是这里也应该提供 `payable` 关键字，否则函数会自动拒绝所有发送给它的以太币。
前半句建议改为：在这里也使用关键字 `payable` 非常重要

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // 这个函数受互斥量保护，这意味着 `msg.sender.call` 中的可重入调用不能再次调用  `f` 。
可重入调用，“可”应该删掉。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +        // `return 7` 语句指定返回值为7，但仍然是在修改器中执行语句 `locked = false` 。
前半句最后，数字 7 前边应该有个空格。（基于中文译文排版规则）。
后半句，建议改为：但修改器中的语句 `locked = false` 仍然会执行。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +如果同一个函数有多个修改器，它们之间以空格隔开，修饰器会依次检查执行。
“修饰器”，应该统一为“修改器”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    在早期的Solidity版本中，有修改器的函数， ``return`` 语句的行为表现不同。
Solidity 两边需要加空格。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +从修改器或函数体的显式的 return 语句仅仅跳出当前的修改器和函数体。 返回变量会被赋值，但整个执行
从修改器或函数体的显式的，建议改为：修改器或函数体中显式的

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +逻辑会在前一个修改器后面定义的 "_" 后继续执行。
建议改为：逻辑会从前一个修改器中的定义的“_”之后继续执行。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +常量
这不是常量，是 constant 状态变量。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +状态变量可以被声明为 ``constant`` 。这种情况下，必须在编译阶段将他们指定为常量。不允许任何访问 storage，区
原文中的第二句和第三句话理解错了。
第二句是说：在这种情况下，只能使用那些在编译时有确定值的表达式来给它们赋值。
第三局是说：任何通过访问 |storage| 、区块链数据（比如 ``now``、``this.balance`` 或 ``block.number``）、执行数据（``msg.gas``）或对外部合约的调用来给它们赋值都是不允许的。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +或调用外部合约。允许表达式可能会对内存分配产生副作用，但不允许可能会对其他内存对象产生
第四句话也理解错了。这句是说：在内存分配上有边界效应（side-effect）的表达式是允许的，但对其他内存对象产生边界效应的表达式则不行。
边界效应，指的是内存的自动扩展机制：如果一个内存对象的大小超过一个“字”，即 32 字节，内存会自动扩展一个“字”来存放这个对象。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +副作用。 允许内置的函数，比如 ``keccak256``，``sha256``，``ripemd160``，``ecrecover``，``addmod``
这句的译法建议参照前几句的译法改为：内建（built-in）的函数 ``keccak256``、``sha256``、``ripemd160``、``ecrecover``、``addmod`` 和 ``mulmod`` 是允许的（即使他们确实会调用外部合约）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +允许内存分配，从而带来可能的副作用的原因是因为这将允许构建复杂的对象，比如，查找表。
理解有误，这句是说：允许带有边界效应的内存分配器的原因是这将允许构建复杂的对象，比如查找表（lookup-table）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +编译器不会为这些变量预留存储，每个使用的常量都会被对应的常量表达式所替换（也许优化器会直接替换为常量表达式的结果值）
后半句建议改为：它们的每次出现都会被替换为相应的常量表达式（这将可能被优化器计算为实际的某个值）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +不是所有的类型都支持常量，当前支持的仅有值类型和字符串。
前半句建议改为：不是所有类型的状态变量都支持用 constant 来修饰

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +可以将函数声明为 ``view`` 类型，这种情况下要保证不修改状态变量。
不修改状态，不是“不修改状态变量”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +#. 写状态变量.
建议意译：修改状态变量

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +#. :ref:`发送事件 <events>`。
emit，译为“发送”不合适，一般可以译为“发出”、“产生”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +  编译器没有强制 ``view`` 方法不能修改状态变量。
修改状态，不是“修改状态变量”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +如果合约中没有与给定的函数标识符匹配的函数，将调用未命名函数（或者如果根本没有提供数据）。
这句译文理解错了。这句原文是说：
如果在一个到合约的调用中，没有其他函数与给定的函数标识符匹配（或没有提供调用数据），那么这个函数（fallback 函数）会被执行。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +此外，当合约收到以太币（没有任何数据），这个函数就会执行。 此外，为了接收以太币，fallback 函数
句首建议改为：而且，每当合约收到以太币 ...

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +在这种上下文中，函数调用通常只消耗很少的 gas（准确地说，2300 个 gas ），所以重要的是使 fallback 函数尽可能便宜。
这句译文逻辑不太准确，建议改为：在这样的上下文中，通常只有很少的 gas 可以用来完成这个函数调用（准确地说，是 2300 gas），所以使 fallback 函数的调用尽量廉价很重要。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +请注意，调用 fallback 函数的交易（而不是内部呼叫）所需的 gas 要高得多，因为每次交易都会额外收取 21000 gas 或更多的费用，
括号里的内容，应该译为“内部调用”，不是“内部呼叫”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +请确保您在部署合约之前彻底测试您的 fallback 函数，以确保执行成本低于 2300 个 gas 。
译文中统一使用“你”，不用“您”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    即使 fallback 函数不能有参数，仍然可以使用 ``msg.data`` 来获取随调用提供的任何有效负载。
payload 译为“数据”即可。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    返还以太币（在Solidity v0.4.0之前行为会有所不同）。 所以如果你想让你的合约接收以太币，必须实现 fallback 函数。
这半句与前半句相连，可以加上“并”返还以太币 ... 。括号里的 Solidity v0.4.0 前后需要加空格。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    一个没有可支付的 fallback 函数的合约，可以作为 `coinbase transaction` （又名 `miner block reward` ）的接收者或者作为 ``selfdestruct`` 的目的地来接收以太币。
payable 是语言关键字，不用翻译。最后半句的“目的地”建议改为“目标”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    对这种以太币转移合约不能作出反应，因此也不能拒绝它们。 这是 EVM 的设计选择，而且 Solidity 无法解决这个问题。
前半句建议改为：一个合约不能对这种以太币转移做出相应
后一句里的 work around 指的是“绕过”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    这也意味着 ``this.balance`` 可以高于合约中实现的一些手工记帐的总和（即，在 fallback 函数中更新的计数器）。
在这个上下文里，counter 译为“累加器”比较合适。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +则选择函数作为重载候选项。如果没有一个候选，解析失败。
最后一句前半句建议改为：如果一个候选都没有

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +通过事件可以方便地使用 EVM 日志记录工具，在一个dapp的接口中，它可以反过来 "调用" Javascript 的监听事件的回调。
这句原文省略了很多内容，建议意译：
事件允许我们方便地使用 EVM 的日志基础设施；我们可以在 dapp 的用户界面中监听事件，EVM 的日志机制可以反过来“调用”用来监听事件的 Javascript 回调函数。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +事件在合约中可被继承。 当他们被调用时，会触发参数存储到交易的日志中 - 一种区块链中的特殊数据结构。
会触发参数存储到交易的日志中，建议改为：会使参数被存储到交易的日志中
后边的破折号需要改为中文破折号。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +这些日志与地址相关联，被并入区块链中，只要区块可以访问就一直存在(至少 Frontier，Homestead 是这样，但 Serenity 也许不是这样)。
括号应该改为中文括号，括号里的内容，建议按原文译为：在 Frontier 和 Homestead 版本中会被永久保存，在 Serenity 版本中可能会改动

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +日志的 SPV 验证是可能的，如果一个外部的实体提供了这样验证的合约，它可以实际检查日志在区块链中是否存在。
建议改为：对日志的 SPV（Simplified Payment Verification）证明是可能的，如果一个外部实体提供了一个带有这种证明的合约，它可以检查日志是否真实存在于区块链中。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +可以最多有三个参数被设置为 ``indexed``，来设置是否被索引：在用户界面上可以按索引参数的特定值来过滤。
建议译为：最多三个参数可以接收 ``indexed`` 属性，这将使它们可以被搜索：在用户界面上可以使用 indexed 参数的特定值来进行过滤。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +如果数组（包括 ``string`` 和 ``bytes``）类型被标记为索引项，则它存储的 Keccak-256 哈希值作为主题索引。
后半句译错了，应该是：则它们的 keccak-256 哈希值会被作为 topic 保存。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +除非你用 ``anonymous`` 说明符声明事件，否则事件签名的哈希值是主题之一。同时也意味着对于匿名事件无法通过名字来过滤。
topic，是日志项中的术语，不要译了。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    索引参数不会自行存储。 你只能按值进行搜索，但不可能检索值本身。
原文的意思是：索引参数本身不会被保存。你只能搜索它们的值（来确定相应的日志数据是否存在），而不能获取它们的值本身。
这是因为标记为 indexed 的参数，是用来生成 Bloom filter 的数据，也就是搜索条件数据，是被变换之后放到 Bloom filter 里的，其原始值并没有保存。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 任何对这个函数的调用（甚至是深度嵌套）都可以过滤被调用的 `Deposit` 来被 JavaScript API 检测到。
译文的语序应该整个调整一下，比如：
我们可以过滤对 `Deposit` 的调用，从而用 Javascript API 来查明对这个函数的任何调用（甚至是深度嵌套调用）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +``logi``  表示总共有带 ``i + 1`` 个 ``bytes32`` 类型的参数。其中第一个参数会被用来做为日志的数据部分，
前半句建议按原文译为：``logi`` 接受 ``i + 1`` 个 ``bytes32`` 类型的参数

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +其它的会做为主题。上面的事件调用可以以相同的方式执行。
topic 是日志数据的术语，建议不译。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +总的继承系统与 `Python's <https://docs.python.org/3/tutorial/classes.html#inheritance>`_, 非常
逗号请改为中文标点。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    // 可以多重继承。 请注意，`owned` 也是 `mortal` 的基类，但只有一个 `owned` 实例（如C ++中的虚拟继承）。
括号里的 C++ 两边需要有空格，但 C 和 ++ 之间不应该有空格。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +    // 如果构造函数接受参数，则需要在头文件中提供（或修改器调用样式）派生合约的构造函数（见下文）。
后半句理解错了，Solidity 里没有“头文件”的概念，这里是说：
则需要在声明（合约的构造函数）时提供（或在派生合约的构造函数位置以修改器调用风格提供（见下文））。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +请注意，我们调用 ``mortal.kill()`` 来调用父合约的销毁请求。这样做法是有问题的，就像
第一句话，建议改为：注意，在上边的代码中，我们调用 ``mortal.kill()`` 来“转发”销毁请求。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +最终的继承序列是 -- 从最远派生合约开始：Final, Base2, Base1, mortal, ownerd）。
破折号请改为中文破折号，两边不用空格。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +Solidity 借鉴了 Python 的方式并且使用 "`C3 线性化 <https://en.wikipedia.org/wiki/C3_linearization>`_" 强制将基类合约转换一个有向无环图(DAG)
引号、括号都需要改为中文标点。引号后边半句建议译为：
来在一个由基类构成的 DAG（有向无环图）中强制为某个特定的顺序。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +的特定顺序。这导致了我们所希望的单调性，但是却禁止了某些继承图。特别是，基类在 ``is`` 后面的顺序很重要。在下面的代码中，Solidity 将会报错
This	results in the desirable property of monotonicity but disallows some inheritance graphs.，这句建议译为：这最终反映为我们所希望的唯一化的结果，但也使某些继承方式变为无效。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +"Linearization of inheritance graph impossible" 。
建议改为：在下面的代码中，Solidity 会给出“Linearization of inheritance graph impossible”这样的错误。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +原因是 ``C`` 请求 ``X`` 重写 ``A`` （因为定义的顺序是 ``A, X``），但是 ``A``本身要求重写
最后的 ``A`` 后边需要有个空格。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +一个指定基类合约的继承顺序的简单原则是从 "most base-like" 到 "most derived"。
译文不够明确，建议改为：
这是一个应该记住的简单规则：以从“最接近的基类”（most base-like）到“最远的继承”（most derived）的顺序来指定所有的基类。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +一种错误情况是继承导致一个合约同时存在相同名字的修改器和函数时。另一种错误情况是继承导致的事件和修改器重名，函数和修改器重名。
译文不通顺，建议改为：
当继承导致一个合约具有相同名字的函数和修改器时，这会被认为是一个错误；当事件和修改器同名，或者函数和事件同名时，同样会被认为是一个错误。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +有一种例外情况，状态变量的 getter 可以覆盖一个公有函数。
这句的 public 建议还是不译。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +合约函数可以缺少实现,如下例所示（请注意函数声明头由 ``;`` 结尾）
逗号需要换为中文标点。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +如果合约继承自抽象合约，并且不通过重写实现所有未实现的函数，那么它本身就是抽象的。
小小的润色：... 并且不通过重写实现 ... 建议改为：... 并且没有通过重写来实现 ...

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +将来可能会解除这些限制。
建议遵照原文译为：将来可能会解除这里的某些限制。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +库与合约类似，但其用途是在指定的地址仅部署一次，并且代码被使用 EVM 的 ``DELEGATECALL`` (Homestead 之前使用 ``CALLCODE`` 关键字)特性。
译文的意思没有理清楚，原文的意思是：
库与合约类似，它们只需要在特定的地址部署一次，并且它们的代码可以通过 EVM 的 ``DELEGATECALL``（Homestead 版本之前是 ``CALLCODE``）特性进行重用。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +因为一个合约是一个独立的代码块，它仅可以访问调用合约明确提供的状态变量（否则无法命名它们）。 如果不修改状态变量（即，如果是 ``view`` 或者 ``pure`` 函数），
第一句的 library 译成合约了。另外这句不够通顺，建议改为：
因为每个库都是一段独立的代码，所以它仅能访问调用合约明确提供的状态变量（否则它就无法通过名字访问这些变量）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +库函数只能被直接调用（即不使用 ``DELEGATECALL`` 关键字），因为库被假定为无状态的。特别是，除非绕过 Solidity 类型系统，否则库不可能破坏。
这两句译文建议优化为：
因为我们假定库是无状态的，所以如果它们不修改状态（也就是说，如果它们是 ``view`` 或 ``pure`` 函数），库函数仅可以通过直接调用来使用（即不使用 ``DELEGATECALL``）。特别是，除非能规避 Solidity 的类型系统，否则是不可能销毁任何库的。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +使用库的合约，可以认为库是隐式的基类合约。虽然它们在继承关系中不会显式可见，但调用库函数与调用显式的基类合约十分类似（如果 ``L`` 是库的话，
第一句的主语搞错了，原文是说：库可以看作是使用他们的合约的隐式的基类合约。
第二句括号里的那句话建议润色为：如果 ``L`` 是库的话，可以使用 ``L.f()`` 来调用库函数

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> + 使用 ``L.f()`` 调用库函数）。此外，就像库是基类一样，对所有使用库的合约，库的 ``internal`` 函数都是可见的。当然，需要使用内部调用约定
就像库是基类一样，建议与前一句统一，译为：就像库是基类合约一样

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> + 来调用内部函数，这意味着所有所有内部类型，内存类型都是通过引用而不是复制来传递。为了在 EVM 中实现这些，内部库函数的代码和从其中调用的所有
所有所有，手误。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +下面的示例说明如何使用库（但是请务必检查 :ref:`using for <using-for>` 有一个实现 set 更好的例子）。
建议润色为：下面的示例说明了如何使用库（但也请务必看看 :ref:`using for <using-for>`，那里有个实现 set 的更好的样例）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +      // 我们定义了一个新的结构体数据类型,用于在调用合约中保存数据。
标点符号用中文标点。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +      // 注意第一个参数是 "storage reference" 类型，因此在调用中参数传递的只是它的存储地址而不是内容。
引号请换为中文标点，两边不需要空格。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +            // 不需要库的特定实例就可以调用库函数，因为当前合约就是 "instance"。
引号请换为中文标点，两边不需要空格。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +由于编译器无法知道库的部署位置，链接器需要填入这些地址必的最终字节码（请参阅 :ref:`commandline-compiler` 以了解如何使用连接器的命令行工具）。 如果这些地址没有作为参数传递给编译器，
后半句译错了，应该是：我们需要通过链接器将这些地址填入最终的字节码中（参阅 :ref:`commandline-compiler` 来了解如何使用命令行编译器来链接字节码）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +替换库中十六进制编码的所有40个符号。
译错了，应该是：将那 40 个字符替换为库合约地址的十六进制编码

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +正如介绍中所述，除调用 ``view`` 或者 ``pure`` 库函数之外，通过 ``CALL`` 而不是 ``DELEGATECALL``
这句理解错了，原文是说：如果库的代码是通过 ``CALL`` 来执行的，而不是 ``DELEGATECALL`` 或 ``CALLCODE``，那么执行的结果会被回退，除非是对 ``view`` 或 ``pure`` 函数的调用。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +的“位置”。生成的代码通过比较这个地址和构造时的地址来确定调用模式。
引号请改为中文标点。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +更具体地说，库的运行时代码总是由 push 指令启用，它在编译时是 20 字节的零。当部署代码运行时，这个常数
由 push 指令启用，应该译为：从一个 push 指令开始

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +调用对象将作为这些函数的第一个参数（像 Python 的 ``self`` 变量）。
译文不准确，建议改为：这些函数将接收到调用它们的对象作为它们的第一个参数（就像 Python 中的 ``self`` 变量）。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +在这两种情况下，所有函数，即使那些与对象类型不匹配的第一参数类型的函数，也被附加上了。
语序不太符合汉语习惯，中间那句也译错了，建议改为：
在这两种情况下，所有函数都会被附加一个参数，即使它们的第一个参数类型与对象的类型不匹配。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +``using A for B;`` 指令仅在当前作用域有效，仅限于在当前合约中，后续可能提升到全局范围。
第二个半句中的 for now 译漏了，还是应该加上，改为“目前仅限于”。

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +注意，所有库调用都是实际的 EVM 函数调用。这意味着如果传递内存或值类型，将执行一个拷贝副本，即使是 ``self`` 变量。
将执行一个拷贝副本，建议改为：都将产生一个副本

2018-05-16 13:03 UTC, riversyang commented on contracts.rst
> +以下示例显示如何使用库的内存类型和内部函数来实现自定义类型，无需外部函数调用的开销：
建议润色为：以下示例展示了如何在库中使用内存类型和内部函数来实现自定义类型，而无需支付外部函数调用的开销。

2018-05-17 07:46 UTC, oldcodeoberyn requested changes

2018-05-17 07:46 UTC, oldcodeoberyn commented on contracts.rst
> +在下面的例子中，``D`` 可以调用 ``c.getData（）`` 来获取 ``data`` 的值，但不能调用 ``f`` 。
in state storage 漏译

2018-05-17 07:46 UTC, oldcodeoberyn commented on contracts.rst
> +编译器自动为所有 **公有** 状态变量创建 getter 函数。 对于下面给出的合约，编译器会生成一个名为 ``data``
**公有** 还是不翻译吧，**public**

2018-05-17 07:46 UTC, oldcodeoberyn commented on contracts.rst
> +修改器的参数可以是任意表达式，在上下文中，所有的函数中引入的符号，在修改器中均可见。在修改器中
建议改为：
修改器的参数可以是任意表达式，在此上下文中，所有在函数中可见的符号，在修改器中均可见

2018-05-17 07:46 UTC, oldcodeoberyn commented on contracts.rst
> +重载函数也存在于外部接口中。 如果两个外部可见函数接收的 Solidity 类型不同但是外部类型相同会导致错误。
“接收的” 从哪里来的？
建议翻译为：
如果两个外部可见函数仅区别于 Solidity 内的类型而不是它们的外部类型则会导致错误。

2018-05-17 07:46 UTC, oldcodeoberyn commented on contracts.rst
> +        // 结果包括对 `Deposit` 的调用参数在内的各种信息。
这里的 result 是指 function(error, result) 传入的参数，不要翻译为“结果” 。
result 包含了 `Deposit` 的调用参数在内的各种信息。

2018-05-17 07:46 UTC, oldcodeoberyn commented on contracts.rst
> +    // 内部函数和状态变量。 不过，这些不可能通过 `this` 来外部访问。
派生合约可以访问所有非私有成员，包括内部函数和状态变量。不过，这些不可能通过 `this` 来外部访问。
->
派生合约可以访问所有非私有成员，包括内部函数和状态变量，但无法通过 `this` 作外部访问。

2018-05-29 06:37 UTC, oldcodeoberyn commented on contracts.rst
> +变量的初始化。
这里别换行，否则会有状态变量间有空格

2018-05-30 01:35 UTC, oldcodeoberyn requested changes

2018-05-30 01:35 UTC, oldcodeoberyn commented on contracts.rst
> +允许内置的函数，内建（built-in）的函数 ``keccak256``，``sha256``，``ripemd160``，``ecrecover``，``addmod``
“允许内置的函数，内建（built-in）的函数 ” 是不是打重了，原文只有 The built-in functions。建议改为：
内建（built-in）函数 ``keccak256``，``sha256``，``ripemd160``，``ecrecover``，``addmod``

2018-05-30 01:35 UTC, oldcodeoberyn commented on contracts.rst
> +
不要增加额外的空行

2018-05-30 01:35 UTC, oldcodeoberyn commented on contracts.rst
> +
不要增加额外的空行

2018-05-30 01:35 UTC, oldcodeoberyn commented on contracts.rst
> +    // 如果构造函数接受参数，则需要在声明（合约的构造函数）时提供（或在派生合约的构造函数位置以修改器调用风格提供（见下文）。
末尾少了一个）

2018-05-30 01:35 UTC, oldcodeoberyn commented on contracts.rst
> +原因是 ``C`` 请求 ``X`` 重写 ``A`` （因为定义的顺序是 ``A, X``），但是 ``A`` 本身要求重写
第一个requests也需翻译为要求

2018-08-16 07:41 UTC, riversyang commented
Pending too long time, close and use another pr to complete this. Thanks @dennisWind .

2018-08-16 07:41 UTC, closed without merging